version: 1.0.{build}
install:
- ps: >-
    New-Item c:\scripts -type directory
    $env:Path += ";C:\scripts"
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat -OutFile "C:\scripts\lein.bat"
    lein self-install
    lein version
build_script:
- cmd: >-
    lein install
    lein deps
test_script:
- cmd: "lein test"